name: CSS Lint & Accessibility

on:
  pull_request:
    paths:
      - '**.css'
      - '**.html'
  push:
    branches: [main, master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências globais
        run: |
          npm install -g stylelint stylelint-config-standard @stylistic/stylelint-plugin postcss pa11y@latest htmlhint

      - name: Lint CSS com Stylelint
        run: |
          echo "Arquivos CSS encontrados:"
          ls -al **/*.css || echo "Nenhum arquivo CSS encontrado"
          npx stylelint "**/*.css" --allow-empty-input

      - name: Lint HTML com HTMLHint
        run: |
          htmlhint '**/*.html' || exit 1

  accessibility:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar Pa11y globalmente
        run: npm install -g pa11y@latest

      - name: Instalar dependências de sandbox do Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev
          export DISPLAY=:99
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Testar acessibilidade com Pa11y em todos os HTML
        run: |
          for file in *.html; do
            pa11y --chrome-launcher-flags="--no-sandbox --disable-setuid-sandbox" file://$PWD/$file || exit 1
          done 